### ISSUE TITLE
this request has no response data available

### ISSUE THREAD

**Issue by sengmitnick** [wanwu/devtools-pro#11]
this request has no response data available

![image](https://user-images.githubusercontent.com/6056366/124222665-c1bb6c00-db34-11eb-954d-b1a25e3d8bc4.png)

![image](https://user-images.githubusercontent.com/6056366/124222679-c97b1080-db34-11eb-9c78-9adceba2620e.png)

**Comment by ksky521** [comment]
这里主要是首先backend的runtime拦截请求的所有情况限制导致的，针对这事情我们加上了代理功能，使用devtools 的network面板来实现fiddler/charles的功能，不过缺点是不能按页面级别的来显示页面内发出的请求，不过可以通过配置过滤器来实现只抓取定向的请求，该功能可以使用next版本试用 `npm i devtools-pro@next`，详细功能可以见文档：https://github.com/wanwu/devtools-pro/blob/main/docs/foxy.md

**Comment by hongrunhui** [comment]
这里主要是首先backend的runtime拦截请求的所有情况限制导致的  这句话啥意思 是有什么限制？
